### ISSUE TITLE
Question: how to apply Policies to BelongsToMany resources?

### ISSUE THREAD

**Issue by andreisusanu** [pktharindu/nova-permissions#10]
Hello,

I'm looking for a way to apply the permissions on the resource's BelongsToMany section. To be more specific, I want to apply a Policy to a BelongsToMany resource.

For example:

- in App\Nova\User resource I have a BelongsToMany field, like this:
`BelongsToMany::make('Roles', 'roles', Role::class)`
- in App\Providers\AuthServiceProvider, I have set the policy:
`'Pktharindu\NovaPermissions\Role' => RolePolicy::class`

Having this BelongsToMany resource, when I view a User, I have a section with the assigned roles, and actions (view/edit/delete) for each role.

[![2.png](https://i.postimg.cc/SRdC9RR3/2.png)](https://postimg.cc/Mfcn2Wym)

Please notice that when I browse the Roles resource, the RolePolicy is properly used.
[![1.png](https://i.postimg.cc/P5xzmWm4/1.png)](https://postimg.cc/RNkHmnp6)

**Comment by pktharindu** [comment]
For that, you can use `attach{Model}` / `detach{Model}` naming convention.

You can find more details on Laravel Nova Doc: https://nova.laravel.com/docs/2.0/resources/authorization.html#relationships

For example, the `RolePolicy` on an app I'm working on looks something like this:
```php
<?php

namespace App\Policies;

use App\Models\User;
use Pktharindu\NovaPermissions\Role;
use Illuminate\Auth\Access\HandlesAuthorization;

class RolePolicy
{
    use HandlesAuthorization;

    public function viewAny(User $user)
    {
        return $user->hasAnyPermission(['view roles', 'view own roles']);
    }

    public function view(User $user, Role $role)
    {
        if ($user->hasPermissionTo('view roles')) {
            return true;
        }

        if ($user->hasPermissionTo('view own roles')) {
            return $role->users()->where('user_id', $user->id)->exists();
        }

        return false;
    }

    public function create(User $user)
    {
        return $user->hasPermissionTo('create roles');
    }

    public function update(User $user, Role $role)
    {
        return $user->hasPermissionTo('edit roles');
    }

    public function delete(User $user, Role $role)
    {
        return $user->hasPermissionTo('delete roles');
    }

    public function attachAnyUser(User $user, Role $role)
    {
        return $user->hasPermissionTo('assign users to roles');
    }

    public function detachUser(User $user, Role $role)
    {
        return $user->hasPermissionTo('assign users to roles');
    }
}
```

I hope this helps.
