### ISSUE TITLE
Config table names not supposed correctly

### ISSUE THREAD

**Issue by ZuggieTM** [pktharindu/nova-permissions#12]
First off, you should edit your Readme to publish and edit the config before publishing migrations and migrating.

Secondly, you have the configuration to specify custom table names, but this doesn't seem to be supported in your models and migrations.  Changing which User model / Resource you're using, plus the tables is all good, but some people might have something not named User, but maybe PublicUser or BackendUser. You should reflect that in both your migrations and code either by adding it to your config, so people can specify the foreign keys or in our code. Same goes for the role and role_user. Some might have it named Team or Group.

I really like the whole feel and look of the package, but making these things customizable would make it even better than it already is.

I for one have a database where backend_user and backend_group is a thing in my DB and I can't change that.

**Comment by pktharindu** [comment]
Yes, you are right. Thanks for pointing that out.
This will be fixed in the next release.
