### ISSUE TITLE
Translate the permissions and buttons text

### ISSUE THREAD

**Issue by gvsrepins** [pktharindu/nova-permissions#14]
Can you please add the option to Translate the permissions and buttons text?

I have highlighted the texts that I wish to translate with you help:

![image](https://user-images.githubusercontent.com/480445/75613975-50b80e80-5b12-11ea-89d4-57982d19c4fe.png)

Thank you!

**Comment by gvsrepins** [comment]
I have notice that I can extend the `Pktharindu\NovaPermissions\Nova\Role` in your role resource and fix this issue without change the plugin. 

Thanks!

**Comment by Khanabeev** [comment]
Can you explain how to fix this problem with translation?
