### ISSUE TITLE
Extend App\Nova\Resource

### ISSUE THREAD

**Issue by pauldstar** [pktharindu/nova-permissions#15]
I see that "Pktharindu\NovaPermissions\Role" extends "Laravel\Nova\Resource".

Wouldn't it be better to extend "App\Nova\Resource" instead. This way we could create methods to be inherited by all child resources.

For example I'd want to be able to ONLY do this:
```
namespace App\Nova;

abstract class Resource extends App\Nova\Resource
{
    public function Breadcrumbs() {};
    public function IndexQuery() {};
    public function AbbreviateLabel() {};
}
```
But at the moment, I'm having to create traits to ensure all resources can inherit; like this:
```
namespace App\Nova;

abstract class Resource extends NovaResource
{
    use Breadcrumbs;
    use SearchesRelations;
    use AbbreviateLabel;
}
```
```
namespace App\Nova;

use Pktharindu\NovaPermissions\Nova\Role as RoleResource;

class Role extends RoleResource
{
    use Breadcrumbs;
    use OrderIndexQueryByName;
    use AbbreviateLabel;
}
```

**Comment by pktharindu** [comment]
Yeah, that makes sense. I'll make a new release fixing this soon!
