### ISSUE TITLE
Error 403 - Permissions & Roles

### ISSUE THREAD

**Issue by luscas** [pktharindu/nova-permissions#17]
I have all the permissions and I can't edit the permission of a role.

### **Roles**
![Roles](https://image.prntscr.com/image/gZ_MT2PpQxiaqR1vZHPQmQ.png)

### **Error**
![Error 403](https://image.prntscr.com/image/osf-zWIUS4anWBp4k1-q9Q.png)

**Comment by pktharindu** [comment]
I'm guessing you don't have the `RolePolicy` setup correctly. Nova redirects to the view page after any updates. Check the `view` method in `RolePolicy`.
