### ISSUE TITLE
Transaltable group name

### ISSUE THREAD

**Issue by vmihaly2020** [pktharindu/nova-permissions#20]
Group name of resource is not translatable

    public static function group()
    {
        return config('nova-permissions.role_resource_group', 'Other');
    }
this should be replaced with 

    public static function group()
    {
        return __(config('nova-permissions.role_resource_group', 'Other'));
    }
in config file translator does not exist.

**Comment by pktharindu** [comment]
Thanks for noting that.

**Comment by pktharindu** [comment]
Closes via v2.1.4
