### ISSUE TITLE
Jumbled layout with longer permission names

### ISSUE THREAD

**Issue by dmason30** [pktharindu/nova-permissions#22]
**Problem** 
It seems that the responsive layout gets a bit jumbled when some of the permissions have longer names:
![image](https://user-images.githubusercontent.com/20278756/95095637-30dd6e80-0723-11eb-9d44-8b2eb84f2d7d.png)

**Cause**
I think use of `flex-auto` on each permission group block is the issue.

**Solution**
If I change this to `flex: 1 1 300px` it displays nicely for me on all screen sizes with some wrapping on the smaller screens which is fine:
<details>
<summary>Details - Screens</summary>

**Desktop**
![image](https://user-images.githubusercontent.com/20278756/95095996-a5181200-0723-11eb-92ae-c58f80a8f505.png)

**Tablet**
![image](https://user-images.githubusercontent.com/20278756/95096938-cd544080-0724-11eb-9c1b-e069de0646ac.png)

**Mobile**
![image](https://user-images.githubusercontent.com/20278756/95097053-f1178680-0724-11eb-9487-f106dd3f065c.png)
</details>

<details>
<summary>Form - Screens</summary>

**Desktop**
![image](https://user-images.githubusercontent.com/20278756/95097620-97fc2280-0725-11eb-94bf-bea16ed27157.png)

**Tablet**
![image](https://user-images.githubusercontent.com/20278756/95097569-874bac80-0725-11eb-805c-334ec8edffa0.png)

**Mobile**
![image](https://user-images.githubusercontent.com/20278756/95097408-5bc8c200-0725-11eb-80cd-501fe76f0116.png)
</details>

I am willing to PR a change once discussed. If you are not willing to change the class then please consider making the views publishable.

**Comment by pktharindu** [comment]
Thanks for the well-explained issue! 
You are right, that looks awful. 😅
I'd appreciate it if you could PR a fix.

**Comment by dmason30** [comment]
See #23
