### ISSUE TITLE
FEATURE REQUEST: Allow developer to hide the "slug" field from the index page

### ISSUE THREAD

**Issue by Fijvect** [pktharindu/nova-permissions#33]
Hello, this is a great tool, thank you for creating it!

Would you consider allowing the developer to hide the "slug" field from the index page? 
Maybe by using the config?

Thank you!

**Comment by pktharindu** [comment]
Thanks! 

Now that I'm thinking about it, the slug field is pretty useless on the index page, isn't it? Maybe it should be hidden by default.
