### ISSUE TITLE
After installation Target class [App\Policies\RolePolicy] does not exist

### ISSUE THREAD

**Issue by RiccardoFrancescato** [pktharindu/nova-permissions#35]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Nova Permissions.
* [x] Checked that your issue isn't already filed.
* [x] Checked if no PR was submitted that fixes this problem.

### Versions

- PHP version: 7.4.20
- Laravel version: 7.30.4
- Nova version: 3.19.1
- Package version: ^2.1

### Description
I have installed the module following the whole procedure but once I reload the page the following error appears:
```
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Policies\RolePolicy] does not exist. (View: /var/www/nova/resources/views/layout.blade.php)
```
![Screenshot 2021-06-25 at 16 13 54](https://user-images.githubusercontent.com/7447963/123437793-59b6d400-d5d0-11eb-9ce3-442546fe792c.png)

I suppose the error is in 
```php

namespace App\Providers;

use App\Policies\UserPolicy;
use App\User;
use App\Models\InfoWeb\Customer as InfoWebCustomer;
use App\Policies\InfoWebCustomerPolicy;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Pktharindu\NovaPermissions\Traits\ValidatesPermissions;

class AuthServiceProvider extends ServiceProvider
{
    use ValidatesPermissions;
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        User::class => UserPolicy::class,
        InfoWebCustomer::class => InfoWebCustomerPolicy::class,
        \Pktharindu\NovaPermissions\Role::class => \App\Policies\RolePolicy::class,
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        foreach (config('nova-permissions.permissions') as $key => $permissions) {
            Gate::define($key, function (User $user) use ($key) {
                if ($this->nobodyHasAccess($key)) {
                    return true;
                }

                return $user->hasPermissionTo($key);
            });
        }
    }
}
```
`\Pktharindu\NovaPermissions\Role::class => \App\Policies\RolePolicy::class,` -> the `RolePolicy::classics missing
### Steps to Reproduce

Install following the procedure

**Expected behavior:**

No errors after following the installation guide

**Actual behavior:** 

Missing `App\Policies\RolePolicy`

**Comment by pktharindu** [comment]
The `RolePolicy::class` doesn't come with the package. So you need to create your own using `php artisan make:policy RolePolicy`.

Let me know if that doesn't work. 🙂

**Comment by RiccardoFrancescato** [comment]
@pktharindu I've created my own `RolePolicy::class` and it's working fine.
Just as suggestion, please consider to edit the installation guide with `php artisan make:policy RolePolicy` instruction or additional it by default in the package. This will help users!
Thanks
Riccardo

**Comment by pktharindu** [comment]
Thanks! Actually, it is already there in the notes here: https://github.com/pktharindu/nova-permissions#create-a-model-policy 🙂

**Comment by akislawek** [comment]
@pktharindu I've stumbled across the same issue as @RiccardoFrancescato, perhaps you'd consider modifying the readme so that the "Create a Model Policy" section comes before "A new resource called Roles will appear in your Nova app after installing this package."?

As I am new to Nova, I was following the instructions step by step, and when I read that "A new resource called Roles will appear in your Nova app after installing this package.", I immediately refreshed my page, only to fine the error mentioned above...

**Comment by pktharindu** [comment]
I just added that bit. Thank you!
