### ISSUE TITLE
Different Users Table

### ISSUE THREAD

**Issue by OITDE** [pktharindu/nova-permissions#38]
Hi!

our users table is named admin_users and our model is named AdminUsers. When I set the user_model and user_resource in the nova-permission config I've got errors when I'm using the hasPermissionTo() in the policies.

I've got a sql error until I have changed the table role_user.user_id to .admin_user_id. But when I want to view the roles the query searches for 'user_id'.

The "error" is in the src/Role.php line 34. There the field 'user_id' is hardcoded. When I change this to 'admin_user_id' everything works again.

Is it possible to make this configurable or is there any other way to not mess with the source?

Thanks!

Regards, Ingo

**Comment by pktharindu** [comment]
What is the error you got after changing the config file?

If you are using something other than the default User model, you can change the `user_model`, `user_resource` and the `table_names.users` values in the config file and it should still work.

**Comment by OITDE** [comment]
We're using a table called admin_users for our backend users.
I've changed the config of nova_permissions to

`'user_model' => 'App\Models\AdminUser',`
`'user_resource' => 'App\Nova\AdminUser',`
```
    'table_names' => [
        'roles' => 'admin_roles',

        'role_permission' => 'admin_role_permission',

        'role_user' => 'admin_role_user',

        'users' => 'admin_users',
    ],

```

I've changed the field name admin_role_user.user_id to admin_role_user.admin_user_id.

If I don't change the fieldname I get an error message from nova:

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'admin_role_user.admin_user_id' in 'field list' (SQL: select 'admin_roles`.*, `admin_role_user`.`admin_user_id` as `pivot_admin_user_id`, `admin_role_user`.`role_id` as `pivot_role_id` from `admin_roles` inner join `admin_role_user` on `admin_roles`.`id` = `admin_role_user`.`role_id` where `admin_role_user`.`admin_user_id` = 1) (View: ..../nova/resources/views/layout.blade.php)

**Comment by pktharindu** [comment]
Fixed! Please upgrade to the latest release ([v2.1.10](https://github.com/pktharindu/nova-permissions/releases/tag/v2.1.10)). It should work without having to change the field names in the migration.

Planing on adding the ability to customize the field names on v3.

**Comment by OITDE** [comment]
Thanks a lot, I'll try.

**Comment by ITango** [comment]
@pktharindu  thanks for the great package.

After updating to 2.1.10 I started to see the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'admin_role.user_id' in 'field list' (SQL: select `roles`.*, `admin_role`.`user_id` as `pivot_user_id`, `admin_role`.`role_id` as `pivot_role_id` from `roles` inner join `admin_role` on `roles`.`id` = `admin_role`.`role_id` where `admin_role`.`user_id` = 1) (View: /home/vagrant/code/vendor/digital-creative/collapsible-resource-manager/resources/views/navigation.blade.php) 

I have the following settings in nova-permissions:
`'user_model' => 'App\Models\Admin'`
`'user_resource' => 'App\Nova\Admin'`

 `'table_names' => [
        'roles' => 'roles',
        'role_permission' => 'role_permission',
        'role_user' => 'admin_role',
        'users' => 'admins',
    ]`

After downgrading to 2.1.9 the error is gone.

Any suggestions on what I need to change to be able to update to 2.1.10?

Thank you

**Comment by pktharindu** [comment]
@ITango have you changed the column names in the migration in any way? Currently, the column names aren't customizable.

**Comment by ITango** [comment]
@pktharindu thank you for the reply.

Yes, I had admin_id in the admin_role table. After changing to user_id it worked. Thank you!
