### ISSUE TITLE
not show role menu in slidebar and user row & detail.

### ISSUE THREAD

**Issue by orchie** [pktharindu/nova-permissions#40]
the version is all lasted, and no error when install.

        "laravel/framework": "^8.54",
        "laravel/nova": " 3.29.0",

I tried default by install steps.
its not show.
then i tried https://github.com/pktharindu/nova-permissions#use-your-own-resources
its not show again.
help~ thanks~

**Comment by pktharindu** [comment]
Can't replicate this without more details. But I just tried it out with a fresh project, and everything seems to work.

![image](https://user-images.githubusercontent.com/23132672/133881013-89d729c6-3433-4edd-bcdf-6a37952874ee.png)

**Comment by orchie** [comment]
Thanks,I find the reason is the file I made  \App\Policies\RolePolicy not correct. so no permission to show Roles menu.
default policy file will deny all requst, and display the menu..,
