### ISSUE TITLE
can't update role

### ISSUE THREAD

**Issue by ikramooe** [pktharindu/nova-permissions#42]
Hello , 
when i try to update a role i get this error 

Unknown permission
C:\xampp\htdocs\qcm\vendor\laravel\framework\src\Illuminate\Foundation\Application.php#1043

any help

**Comment by pktharindu** [comment]
Hello 👋🏻
Are you doing anything different from the [installation instructions](https://github.com/pktharindu/nova-permissions#installation)? Can you please provide more details?

**Comment by pktharindu** [comment]
Feel free to reopen with more details. 🙂
