### ISSUE TITLE
Create Policy for Role?

### ISSUE THREAD

**Issue by sunb** [pktharindu/nova-permissions#5]
I want to limit only Administrator Role can mange Role. So I created a Policy for Role 

```
namespace App\Policies;

use Pktharindu\Nova\Permissions\Role;
use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class RolePolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any roles.
     *
     * @param  \App\User  $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
        return false;
    }

    /**
     * Determine whether the user can view the role.
     *
     * @param  \App\User  $user
     * @param  \App\Role  $role
     * @return mixed
     */
    public function view(User $user, Role $role)
    {
        //
    }
```
but all users have access to Role Resource. How to make a Policy for Role?

**Comment by sunb** [comment]
I created a new model name App\Role. 
Extend from `Pktharindu\Nova\Permissions\Role `
Create custom Role Resource in Nova, extend from `Pktharindu\Nova\Permissions\Nova\Role`
Override custom Role Resource to use App\Role as Model

**Comment by myfender** [comment]
Sorry, I didn't understand this point ... I can't make permissions work, everyone can do anything. Do you have a working example?
