### ISSUE TITLE
superadmin edit role bug

### ISSUE THREAD

**Issue by raonikhil** [pktharindu/nova-permissions#53]
Everything is working fine (great work!) except for this one update issue for a role called superadmin. The edit role is working for any role that I define but when I try to update a role which is named 'superadmin', it redirects me to 403 error page like this with an error message showing: `There was a problem submitting the form: Forbidden`. 

In the `RolePolicy.php` , i have the update method defined like this
```
public function update(User $user, Role $role)
{
        if ($user->hasPermissionTo('create roles')) {
            return true;
        }
}
```

The `boot` function in the `AuthServiceProvider.php`:
```
public function boot()
    {
        $this->registerPolicies();

        foreach (config('nova-permissions.permissions') as $key => $permissions) {
            Gate::define($key, function (User $user) use ($key) {
                if ($this->nobodyHasAccess($key)) {
                    return true;
                }

                return $user->hasPermissionTo($key);
            });
        }
    }
```

![image](https://user-images.githubusercontent.com/2131177/166907091-144c2c76-ae38-488d-9b1d-f18f1baf0fc7.png)

Am I doing something wrong here? help!

**Comment by pktharindu** [comment]
Sounds like it is related to the way you have defined the `RolePolicy`. When you update a role, it redirects you to its view page. So, make sure you are not losing permission to do so when you update it. 🙂

**Comment by raonikhil** [comment]
I think I know when this issue happens: when there is an existing permission that is assigned to a role and if that permission gets updated or deleted then that role can not be updated anymore which gives the above mentioned error.

**Comment by pktharindu** [comment]
Glad you could figure it out ✌🏻
