### ISSUE TITLE
What's in role.php

### ISSUE THREAD

**Issue by pslxx** [pktharindu/nova-permissions#7]
???

**Comment by pktharindu** [comment]
Can you be more specific? What is the problem you are facing?

**Comment by pslxx** [comment]
You can see the file role.php, which is not roleclass

**Comment by pktharindu** [comment]
Oh Boy! Thank you so much for pointing that out. 💯 
No idea how that happened exactly. But my code editor has been acting weird lately.
Anyway, try using the new release.
Cheers!
