### ISSUE TITLE
Enable translations by default

### ISSUE THREAD

**Issue by OliverZiegler** [pktharindu/nova-permissions#8]
Hi there, nice package that totally fits our needs.

Do you think of enabling more translations by default?

The following parts are currently missing the helper:
* ~~for the Role Resource label and singularLabel~~ overlooked, this already exists 🙈 
* when population the permission checkboxes for `group`, `display_name` and `description`

**Comment by pktharindu** [comment]
Thank you so much for your kind words. ❤

I actually had the intention of making this translatable when developing this package, but we ended up only using English. So never really got around to testing this. Thanks for pointing this out.
