### ISSUE TITLE
Default Users and Roles permission not workin.

### ISSUE THREAD

**Issue by romarmillan91** [pktharindu/nova-permissions#9]
Hi,

Great package overall.

I installed and used it as per documented. But the default user and roles permissions doesnt seem to work. I tested creating new resource policy and added the permission on the config which worked. I created a different role and assigned it to a different user as well. Unchecked all permissions on Users and Roles but I can still manipulate the Users and Roles resources.

Have I missed something regarding about this?

**Comment by pktharindu** [comment]
Thank you for your kind words.
Did you also try registering the policies under `AuthServiceProvider`?

**Comment by romarmillan91** [comment]
Yes, I did.
I added ValidatesPermissions and the bit for automatically registering the gates.
What's add tho is when I tried adding my own permission and policy for a different resource, it works as per documented.
Just the default User and Role resource permissions are not working.

**Comment by pktharindu** [comment]
This package doesn't come with any policies built-in. The permissions defined in the config is only an example. So you will still have to create policies for both `Role` and `User` models.
Also, since the `Role` model is not in your default model name-space, auto registering won't work.
In your `AuthServiceProvider ` you should do something like:

```php
protected $policies = [
    \Pktharindu\NovaPermissions\Role::class => \App\Policies\RolePolicy::class,
];
```

**Comment by myfender** [comment]
Sorry, I didn't understand this point ... I can't make permissions work, everyone can do anything. Do you have a working example?

**Comment by pktharindu** [comment]
For authorization, this package uses [Laravel Policies](https://laravel.com/docs/7.x/authorization#creating-policies) under the hood. So for each `Resource` you want to authorize user actions against, you need to create a `Policy` class as described in the [Usage](https://github.com/pktharindu/nova-permissions#usage) section. You can follow the [Laravel Nova documentation](https://nova.laravel.com/docs/3.0/resources/authorization.html#policies) to see which methods are available for you.
